import type { DiccionarioEntry } from '@/contracts/config'
import { SEGMENTOS } from './segmentos'
import { normalizeText } from '@/ingest/normalize'

const porN3 = new Map(SEGMENTOS.map((s) => [s.n3, s]))

// Cada variante hereda macro y código del catálogo oficial — el diccionario nunca puede apuntar a
// un segmento fuera de los 14 (un typo aquí revienta en build, no en producción).
const E = (variante: string, n3: string): DiccionarioEntry => {
  const seg = porN3.get(n3)
  if (!seg) throw new Error(`Diccionario: segmento desconocido '${n3}' para variante '${variante}'`)
  return { variante, segmentoN3: seg.n3, macroN1: seg.macroN1, codigo: seg.codigo, metodo: 'EXACTO', activa: true }
}

// Fuente: Entregable 2.1 Hoja 4 MATRIZ_EQUIVALENCIAS remapeada al catálogo oficial de 14
// segmentos, ampliada con las variantes reales observadas en los consolidados Sell Out
// OCT-25→MAR-26 y 2026 H1/H2 (≈820K filas). La regla de valores combinados se mantiene:
// gana el primer término («ABASTOS / BODEGAS» → Abastos, «LICORERIAS/BARES/BODEGONES» →
// Licorerias y Bares).
export const DICCIONARIO: DiccionarioEntry[] = [
  // ── Abastos ──
  E('ABASTOS', 'Abastos'),
  E('ABASTO', 'Abastos'),
  E('ABASTOS TRADICIONALES', 'Abastos'),
  E('ABASTO GRANDE', 'Abastos'),
  E('ABASTO MEDIANO', 'Abastos'),
  E('ABASTO PEQUEÑO', 'Abastos'),
  E('09 Abasto- Bod- Puest m', 'Abastos'),
  E('ABASTOS / BODEGAS', 'Abastos'),
  E('ABASTOS, BODEGAS', 'Abastos'),
  E('ABASTO/BODEGA', 'Abastos'),
  E('ABASTO BODEGA', 'Abastos'),
  E('ABASTO, MINI MARKET, BODEGONES', 'Abastos'),
  E('PUESTO DE MERCADO', 'Abastos'),
  E('PUESTOS DE MERCADO', 'Abastos'),
  E('MERCADO MUNICIPALES', 'Abastos'),
  E('MERCADO MUNICIPAL', 'Abastos'),
  E('PTO MERCADO/KIOSKO', 'Abastos'),
  E('VIVERES', 'Abastos'),

  // ── Bodegas ──
  E('BODEGAS', 'Bodegas'),
  E('BODEGA', 'Bodegas'),

  // ── Bodegones ──
  E('BODEGONES', 'Bodegones'),
  E('BODEGON', 'Bodegones'),
  E('BODEGON/ LICORERIAS', 'Bodegones'),
  E('BODEGON/ MINI MARKET', 'Bodegones'),
  E('BODEGON-LICORERIA', 'Bodegones'),

  // ── Carniceria, charcuteria y Frigorifico ──
  E('CARNICERIA, CHARCUTERIA Y FRIGORIFICO', 'Carniceria, charcuteria y Frigorifico'),
  E('CARNICERIA / CHARCUTERIA / FRIGORIFICO', 'Carniceria, charcuteria y Frigorifico'),
  E('CARNICERÍA/CHARCUTERÍA/FRIGORÍFICO.', 'Carniceria, charcuteria y Frigorifico'),
  E('FRIGORIFICO Y CHARCUTERIA', 'Carniceria, charcuteria y Frigorifico'),
  E('FRIGORIFICO / CARNICERIA / CHARCUTERIA', 'Carniceria, charcuteria y Frigorifico'),
  E('CARNICERÍAS/CHARCUTERÍAS', 'Carniceria, charcuteria y Frigorifico'),
  E('CARNICERIAS', 'Carniceria, charcuteria y Frigorifico'),
  E('CARNICERIA', 'Carniceria, charcuteria y Frigorifico'),
  E('CARNICERIA/CHARCUTERIA', 'Carniceria, charcuteria y Frigorifico'),
  E('CHARCUTERIAS/FRIGORIFICOS/CARNICERIAS', 'Carniceria, charcuteria y Frigorifico'),
  E('CHARCUTERIAS/FRIGORIFICO/CARNICERIA', 'Carniceria, charcuteria y Frigorifico'),
  E('FRIGORIFICO', 'Carniceria, charcuteria y Frigorifico'),
  E('FRIGORIFICOS', 'Carniceria, charcuteria y Frigorifico'),
  E('CHARCUTERIAS', 'Carniceria, charcuteria y Frigorifico'),
  E('CHARCUTERIA', 'Carniceria, charcuteria y Frigorifico'),
  E('CARNICERIAS/CHARCUTERIA', 'Carniceria, charcuteria y Frigorifico'),
  E('CARNICERIA CHARCUTERIA', 'Carniceria, charcuteria y Frigorifico'),
  E('CHARCUTERIA Y CARNICERIA', 'Carniceria, charcuteria y Frigorifico'),
  E('FRIGORIFICO- CARNICERIA', 'Carniceria, charcuteria y Frigorifico'),
  E('CARNICERIA - FRIGORIFICO', 'Carniceria, charcuteria y Frigorifico'),
  E('VIVERES Y CHARCUTERI', 'Carniceria, charcuteria y Frigorifico'),
  E('CARNICERIA Y CHARCUTERIA', 'Carniceria, charcuteria y Frigorifico'),
  E('CARNICERIA MINIMARKET', 'Carniceria, charcuteria y Frigorifico'),

  // ── Farmacias (tradicionales, modernas y cadenas: todas al mismo segmento oficial) ──
  E('FARMACIAS', 'Farmacias'),
  E('FARMACIA', 'Farmacias'),
  E('FARMACIA INDEPENDIENTE', 'Farmacias'),
  E('FARMACIAS CLASICAS', 'Farmacias'),
  E('FARMACIAS TRADICIONALES', 'Farmacias'),
  E('FARMACIA MOSTRADOR', 'Farmacias'),
  E('FARMACIA TRADICIONAL', 'Farmacias'),
  E('FARMACIA TRADICIONAL (MOSTRADOR)', 'Farmacias'),
  E('FARMACIAS Y PERFUMERIAS TRADICIONALES', 'Farmacias'),
  E('FARMACIAS GRANDES', 'Farmacias'),
  E('FARMACIA CON AUTOSERVICIO', 'Farmacias'),
  E('FARMACIA AUT SERVICIO', 'Farmacias'),
  E('07 FARMACIA AUTOSER.', 'Farmacias'),
  E('FARMACIAS MODERNAS', 'Farmacias'),
  E('FARMACIA MODERNA', 'Farmacias'),
  E('FARMACIA CADENA', 'Farmacias'),
  E('FARMACIAS CADENAS', 'Farmacias'),
  E('FARM. PEQUEÑAS', 'Farmacias'),
  E('FARM. DE MOSTRADOR', 'Farmacias'),

  // ── Horeca (hoteles, restaurantes, cafeterías, foodservice) ──
  E('HORECA', 'Horeca'),
  E('RESTAURANTE', 'Horeca'),
  E('RESTAURANT', 'Horeca'),
  E('RESTAURANTES', 'Horeca'),
  E('RESTAURANT FAMILIAR', 'Horeca'),
  E('RESTAURANT / BAR', 'Horeca'),
  E('BAR/RESTAURANT', 'Horeca'),
  E('RESTAURANT / BAR DE LUJO', 'Horeca'),
  E('RESTAURANTES/PIZZERÍAS', 'Horeca'),
  E('RESTAURANTE O CAFETERIA', 'Horeca'),
  E('RESTAURANTES O CAFETERÍA', 'Horeca'),
  E('RESTAURANTE/VIVERES', 'Horeca'),
  E('RESTAURANT MINI MARKET', 'Horeca'),
  E('REST/BARES/TASCAS', 'Horeca'),
  E('FAST FOOD', 'Horeca'),
  E('STREET FOOD', 'Horeca'),
  E('HAMBURGUESERÍA', 'Horeca'),
  E('PIZZERIA', 'Horeca'),
  E('CAFETERIA / LUNCHERIAS', 'Horeca'),
  E('LUNCHERIA', 'Horeca'),
  E('LUNCHERIA / CAFETERIA', 'Horeca'),
  E('LONCHERIA', 'Horeca'),
  E('FUENTES DE SODA/LUNCHERÍAS', 'Horeca'),
  E('FUENTES DE SODA/LUNCHERIAS/CAF', 'Horeca'),
  E('FUENTE DE SODA', 'Horeca'),
  E('CAFETERIA', 'Horeca'),
  E('CAFETERIAS', 'Horeca'),
  E('CAFETERIAS/SIMILARES', 'Horeca'),
  E('CAFET/LUNCH/REST/BAR', 'Horeca'),
  E('CAFETIN', 'Horeca'),
  E('HOTELES', 'Horeca'),
  E('HOTELES Y POSADAS', 'Horeca'),
  E('HOTEL - RESTAURANT', 'Horeca'),
  E('HOTEL / POSADA', 'Horeca'),
  E('HOTELERIA', 'Horeca'),
  E('FOODSERVICE', 'Horeca'),
  E('FOODSERVICES', 'Horeca'),
  E('FOOD SERVICE', 'Horeca'),
  E('CATERING / INSTITUCIONAL', 'Horeca'),
  E('INSTITUCIONALES', 'Horeca'),
  E('CANTINA ESCOLAR', 'Horeca'),
  E('HELADERIA', 'Horeca'),
  E('HELADERIAS', 'Horeca'),
  E('ON PREMISE', 'Horeca'),
  E('COMPRAS A CONVENIENCIA', 'Horeca'),

  // ── Kioscos (incluye kioscos de confites, que se integran a la base — no van al CEC) ──
  E('KIOSCOS', 'Kioscos'),
  E('KIOSCO', 'Kioscos'),
  E('KIOSKOS', 'Kioscos'),
  E('KIOSKO', 'Kioscos'),
  E('KIOSKO REVISTA', 'Kioscos'),
  E('KIOSCOS/PUESTOS DE MERCADOS', 'Kioscos'),
  E('REFRESQUERIAS/KIOSKOS', 'Kioscos'),
  E('KIOSCOS DE CONFITES', 'Kioscos'),
  E('KIOSCO DE CONFITES', 'Kioscos'),
  E('CONFITERIA', 'Kioscos'),
  E('CONFITERIAS', 'Kioscos'),
  E('PIÑATERIA CONFITERIA', 'Kioscos'),

  // ── Licorerias y Bares ──
  E('LICORERIAS Y BARES', 'Licorerias y Bares'),
  E('LICORERIAS', 'Licorerias y Bares'),
  E('LICORERIA', 'Licorerias y Bares'),
  E('LICORES', 'Licorerias y Bares'),
  E('21 Licoreria', 'Licorerias y Bares'),
  E('LICORERÍAS/BODEGONES', 'Licorerias y Bares'),
  E('LICORERIAS/BARES/BODEGONES', 'Licorerias y Bares'),
  E('LICORERÍAS/BODEGOFAS', 'Licorerias y Bares'),
  E('ALCOHOL CERVEZA VINO', 'Licorerias y Bares'),
  E('BARES', 'Licorerias y Bares'),

  // ── Mayoristas ──
  E('MAYORISTAS', 'Mayoristas'),
  E('MAYORISTA', 'Mayoristas'),
  E('MAYORISTAS CON FDV', 'Mayoristas'),
  E('MAYORISTAS CON FDF', 'Mayoristas'),
  E('MAYORISTA C/FUERZA DE VENTA', 'Mayoristas'),
  E('MAYORISTA CON FUERZA DE VENTA', 'Mayoristas'),
  E('MAYORISTAS SIN FDV', 'Mayoristas'),
  E('MAYORISTA S/FUERZA DE VENTA', 'Mayoristas'),
  E('MAYORISTA SIN FUERZA DE VENTA', 'Mayoristas'),
  E('08 MAYORISTA- CONF- DIS', 'Mayoristas'),
  E('DISTRIBUIDORES', 'Mayoristas'),
  E('DISTRIBUIDORA', 'Mayoristas'),
  E('DISTRIBUIDORAS', 'Mayoristas'),
  E('DISTRIBUIDOR', 'Mayoristas'),
  E('DISTRIBUIDOR MAYORISTA', 'Mayoristas'),
  E('DISTRIBUIDORA/COMERCIALIZADORA', 'Mayoristas'),
  E('COMERCIALIZADORA', 'Mayoristas'),
  E('NANO DISTRIBUIDOR', 'Mayoristas'),
  E('NANO DISTRIBUIDORES', 'Mayoristas'),
  E('SUB-DISTRIBUIDOR', 'Mayoristas'),
  E('SUB-DISTRIBUIDORES', 'Mayoristas'),

  // ── Otros (segmento per se del catálogo: agrupa lo definido que no calza en los 13 específicos;
  //     los EMPLEADOS también van aquí — la exclusión de la medición se hace a lo interno con la
  //     columna valor_original_segmento, que siempre conserva el crudo) ──
  E('OTROS', 'Otros'),
  E('OTRO', 'Otros'),
  E('OT', 'Otros'),
  E('OTROS CLIENTES CANAL BAJO', 'Otros'),
  E('CANAL BAJO', 'Otros'),
  E('EMPLEADOS', 'Otros'),
  E('EMPLEADO', 'Otros'),
  E('VENTAS AL PERSONAL', 'Otros'),
  E('PERSONAL OFICINA', 'Otros'),
  E('VENTAS INTERNAS', 'Otros'),
  E('VENTAS POR OFICINA', 'Otros'),
  E('CONSUMO INTERNO', 'Otros'),
  E('OFICINA', 'Otros'),
  E('PERSONA NATURAL', 'Otros'),
  E('PERFUMERIAS', 'Otros'),
  E('PERFUMERIA', 'Otros'),
  E('PERFUMERIA INDEPENDIENTE', 'Otros'),
  E('PERF. PEQUEÑAS', 'Otros'),
  E('04 Perfumerias Tradic.', 'Otros'),
  E('05 Perfumerias Autoser.', 'Otros'),
  E('FERRETERIAS', 'Otros'),
  E('FERRETERIA', 'Otros'),
  E('12 Ferret-Bazares-Quinc', 'Otros'),
  E('QUINCALLERIA', 'Otros'),
  E('QUINCALLA', 'Otros'),
  E('QUINCALLAS', 'Otros'),
  E('QUINCALLERIA Y REFRE', 'Otros'),
  E('QUINCALLERIA/MISCELANEOS', 'Otros'),
  E('FRUTERIA', 'Otros'),
  E('FRUTERIAS', 'Otros'),
  E('FERIAS DE VERDURAS / FRUTERAS', 'Otros'),
  E('FERIA DE HORTALIZAS/VERDURAS/FRUTERIAS', 'Otros'),
  E('FERIAS DE HORTALIZAS/VERDURAS/FRUTERÍAS', 'Otros'),
  E('TIENDA PARA BEBE', 'Otros'),
  E('PIÑATERIAS', 'Otros'),
  E('PIÑATERIA', 'Otros'),
  E('TIENDAS DE REGALO', 'Otros'),
  E('LIBRERIAS, PAPELERIAS', 'Otros'),
  E('LIBRERIA', 'Otros'),
  E('PAPELERIA', 'Otros'),
  E('PET SHOP', 'Otros'),
  E('AGROPECUARIA', 'Otros'),
  E('AGROPECUARIAS', 'Otros'),
  E('AGROPECUARIA/ AGROPET / CLINICAS', 'Otros'),
  E('AGROPUNTO', 'Otros'),
  E('AGROPUNTOS', 'Otros'),
  E('CASAS AGRICOLAS', 'Otros'),
  E('BARBERIAS, PELUQUERIAS', 'Otros'),
  E('PELUQUERIA', 'Otros'),
  E('CYBERCAFE', 'Otros'),
  E('CYBER CAFÉ', 'Otros'),
  E('TIENDA DE COMESTICO', 'Otros'),
  E('CUIDADO PERSONAL', 'Otros'),
  E('ART. LIMPIEZA', 'Otros'),
  E('LUBRICANTES', 'Otros'),
  E('JUEGOS Y OCIO', 'Otros'),
  E('VARIEDADES', 'Otros'),
  E('MULTITIENDA', 'Otros'),
  E('INDUSTRIAS/FABRICAS', 'Otros'),
  E('INDUSTRIAS/FÁBRICAS', 'Otros'),
  E('EMPRESA DE CONSUMO', 'Otros'),
  // Canal moderno (cadenas): fuera del alcance DTT, se reporta como Otros para no perder el volumen.
  E('CADENAS NACIONALES', 'Otros'),
  E('CADENAS', 'Otros'),
  E('CADENAS REGIONALES', 'Otros'),
  E('CADENAS DE SUPER. REGIONAL', 'Otros'),
  E('SUPERMERCADOS CADENAS', 'Otros'),
  E('HIPERMERCADOS', 'Otros'),
  E('HIPERMERCADO', 'Otros'),
  E('HIPERMERCADO/CASH & CARRY', 'Otros'),
  E('CASH & CARRY', 'Otros'),

  // ── Panaderias y Pastelerias ──
  E('PANADERIAS Y PASTELERIAS', 'Panaderias y Pastelerias'),
  E('PANADERIAS', 'Panaderias y Pastelerias'),
  E('PANADERIA', 'Panaderias y Pastelerias'),
  E('PANADERIA Y PASTELERIA', 'Panaderias y Pastelerias'),
  E('PANADERIAS / PASTELERIA', 'Panaderias y Pastelerias'),
  E('PANADERIA/PASTELERIA', 'Panaderias y Pastelerias'),
  E('PANDERIA', 'Panaderias y Pastelerias'),
  E('10 Panaderias', 'Panaderias y Pastelerias'),
  E('PASTELERIA', 'Panaderias y Pastelerias'),
  E('PASTELERIAS', 'Panaderias y Pastelerias'),
  E('REPOSTERIA', 'Panaderias y Pastelerias'),
  E('REPOSTERIAS', 'Panaderias y Pastelerias'),
  E('REPOSTERIA/UTILIZADORES', 'Panaderias y Pastelerias'),
  E('CASA REPOSTERIA', 'Panaderias y Pastelerias'),
  E('PANIFICADORA', 'Panaderias y Pastelerias'),
  E('PANIFICADORAS', 'Panaderias y Pastelerias'),
  E('BAKERY', 'Panaderias y Pastelerias'),
  E('DULCERIA', 'Panaderias y Pastelerias'),

  // ── SMI (supermercados independientes; el tamaño ya no distingue segmento) ──
  E('SMI', 'SMI'),
  E('SUPERMERCADO', 'SMI'),
  E('SUPERMERCADOS', 'SMI'),
  E('SUPER MERCADO', 'SMI'),
  E('SUPERMERCADO INDEPENDIENTE', 'SMI'),
  E('SUPERMERCADOS INDEPENDIENTES', 'SMI'),
  E('SUPERMERCADO INDEPENDIENTES', 'SMI'),
  E('SUP INDEPENDIENTE', 'SMI'),
  E('SUPER. GRANDES', 'SMI'),
  E('01 Super. Grandes', 'SMI'),
  E('SPM INDEPENDIENTE GRANDE', 'SMI'),
  E('Supermercados Grandes.', 'SMI'),
  E('SUPERMERCADO GRANDE', 'SMI'),
  E('SUPERMERCADO INDEPENDIENTE GRA', 'SMI'),
  E('SUPERMERCADO MEDIANO', 'SMI'),
  E('SUPER. MEDIANOS', 'SMI'),
  E('SPM INDEPENDIENTE PEQUEÑO', 'SMI'),
  E('02 Super. Pequeños', 'SMI'),
  E('SUPERMERCADO PEQUEÑO', 'SMI'),
  E('AUTOMERCADO', 'SMI'),
  E('AUTOMERCADOS', 'SMI'),
  E('SUPERMERCADO Y AUTOMERCADO', 'SMI'),

  // ── SMI - Mini Market ──
  E('SMI - MINI MARKET', 'SMI - Mini Market'),
  E('MINI MARKET', 'SMI - Mini Market'),
  E('MINI MARKETS', 'SMI - Mini Market'),
  E('MINIMARKET', 'SMI - Mini Market'),
  E('MINIMARKETS', 'SMI - Mini Market'),
  E('MINIMARTS', 'SMI - Mini Market'),
  E('SUPER. MINIMARTS', 'SMI - Mini Market'),
  E('MINIMERCADO', 'SMI - Mini Market'),
  E('MINI MERCADO', 'SMI - Mini Market'),
  E('MINI SUPERMERCADO', 'SMI - Mini Market'),

  // ── Tiendas de conveniencias ──
  E('TIENDAS DE CONVENIENCIAS', 'Tiendas de conveniencias'),
  E('TIENDA DE CONVENIENCIA', 'Tiendas de conveniencias'),
  E('TIENDAS DE CONVENIENCIA', 'Tiendas de conveniencias'),
  E('13 Tiendas de Convenenc', 'Tiendas de conveniencias'),
  E('ESTACION DE SERVICIO', 'Tiendas de conveniencias'),
  E('ESTACION PETROLERA', 'Tiendas de conveniencias'),
]

// Garantiza en build/test que ninguna variante colisiona tras normalizar (dos textos distintos
// que normalizan igual serían una entrada muerta — buildIndex se queda con la primera).
export function variantesDuplicadas(): string[] {
  const vistos = new Set<string>()
  const dups: string[] = []
  for (const e of DICCIONARIO) {
    const key = normalizeText(e.variante)
    if (vistos.has(key)) dups.push(e.variante)
    vistos.add(key)
  }
  return dups
}
