// Fuente: Entregable 2.1 Hoja 2 CATALOGO_ESTADOS (24 oficiales)
export const ESTADOS: string[] = [
  'AMAZONAS',
  'ANZOATEGUI',
  'APURE',
  'ARAGUA',
  'BARINAS',
  'BOLIVAR',
  'CARABOBO',
  'COJEDES',
  'DELTA AMACURO',
  'DISTRITO CAPITAL',
  'FALCON',
  'GUARICO',
  'LARA',
  'MERIDA',
  'MIRANDA',
  'MONAGAS',
  'NUEVA ESPARTA',
  'PORTUGUESA',
  'SUCRE',
  'TACHIRA',
  'TRUJILLO',
  'VARGAS',
  'YARACUY',
  'ZULIA',
]
