// PLACEHOLDER — replace with catalogo_estados.csv (Entregable 3.1). VE political division (24).
export const ESTADOS: string[] = [
  'AMAZONAS',
  'ANZOATEGUI',
  'APURE',
  'ARAGUA',
  'BARINAS',
  'BOLIVAR',
  'CARABOBO',
  'COJEDES',
  'DELTA AMACURO',
  'DISTRITO CAPITAL',
  'FALCON',
  'GUARICO',
  'LA GUAIRA',
  'LARA',
  'MERIDA',
  'MIRANDA',
  'MONAGAS',
  'NUEVA ESPARTA',
  'PORTUGUESA',
  'SUCRE',
  'TACHIRA',
  'TRUJILLO',
  'YARACUY',
  'ZULIA',
]
