import type { SegmentoSeed } from '@/contracts/config'

// Fuente: Entregable 2.1 Hoja 1 JERARQUIA_SEGMENTOS. La tabla lista 37 N3 codificados; el
// "Resumen de Cobertura" del doc dice 35 (cifra desactualizada) — la tabla es la fuente válida (regla R5).
export const SEGMENTOS: SegmentoSeed[] = [
  { n3: 'ABASTO', macroN1: 'TRADE TRADICIONAL (UTT)', codigo: 'UTT-01', placeholder: false },
  { n3: 'BODEGA', macroN1: 'TRADE TRADICIONAL (UTT)', codigo: 'UTT-02', placeholder: false },
  { n3: 'PUESTO DE MERCADO', macroN1: 'TRADE TRADICIONAL (UTT)', codigo: 'UTT-03', placeholder: false },
  { n3: 'KIOSCO', macroN1: 'TRADE TRADICIONAL (UTT)', codigo: 'UTT-04', placeholder: false },
  { n3: 'PANADERIA', macroN1: 'TRADE TRADICIONAL (UTT)', codigo: 'UTT-05', placeholder: false },
  { n3: 'PASTELERIA', macroN1: 'TRADE TRADICIONAL (UTT)', codigo: 'UTT-06', placeholder: false },
  { n3: 'CARNICERIA / CHARCUTERIA / FRIGORIFICO', macroN1: 'TRADE TRADICIONAL (UTT)', codigo: 'UTT-07', placeholder: false },
  { n3: 'LICORERIA', macroN1: 'TRADE TRADICIONAL (UTT)', codigo: 'UTT-08', placeholder: false },
  { n3: 'CONFITERIA', macroN1: 'TRADE TRADICIONAL (UTT)', codigo: 'UTT-09', placeholder: false },
  { n3: 'FARMACIA TRADICIONAL (MOSTRADOR)', macroN1: 'TRADE TRADICIONAL (UTT)', codigo: 'UTT-10', placeholder: false },
  { n3: 'PERFUMERIA TRADICIONAL', macroN1: 'TRADE TRADICIONAL (UTT)', codigo: 'UTT-11', placeholder: false },
  { n3: 'FERRETERIA / QUINCALLERIA', macroN1: 'TRADE TRADICIONAL (UTT)', codigo: 'UTT-12', placeholder: false },
  { n3: 'SUPERMERCADO INDEPENDIENTE GRANDE', macroN1: 'SUPERMERCADOS INDEPENDIENTES', codigo: 'SI-01', placeholder: false },
  { n3: 'SUPERMERCADO INDEPENDIENTE MEDIANO', macroN1: 'SUPERMERCADOS INDEPENDIENTES', codigo: 'SI-02', placeholder: false },
  { n3: 'SUPERMERCADO INDEPENDIENTE PEQUEÑO', macroN1: 'SUPERMERCADOS INDEPENDIENTES', codigo: 'SI-03', placeholder: false },
  { n3: 'AUTOMERCADO', macroN1: 'SUPERMERCADOS INDEPENDIENTES', codigo: 'SI-04', placeholder: false },
  { n3: 'MINI MARKET', macroN1: 'SUPERMERCADOS INDEPENDIENTES', codigo: 'SI-05', placeholder: false },
  { n3: 'CADENA NACIONAL', macroN1: 'CADENAS', codigo: 'CAD-01', placeholder: false },
  { n3: 'CADENA REGIONAL', macroN1: 'CADENAS', codigo: 'CAD-02', placeholder: false },
  { n3: 'HIPERMERCADO / CASH & CARRY', macroN1: 'CADENAS', codigo: 'CAD-03', placeholder: false },
  { n3: 'FARMACIA CON AUTOSERVICIO', macroN1: 'FARMACIAS MODERNAS', codigo: 'FM-01', placeholder: false },
  { n3: 'FARMACIA CADENA', macroN1: 'FARMACIAS MODERNAS', codigo: 'FM-02', placeholder: false },
  { n3: 'FARMACIA MODERNA INDEPENDIENTE', macroN1: 'FARMACIAS MODERNAS', codigo: 'FM-03', placeholder: false },
  { n3: 'BODEGON', macroN1: 'BODEGONES', codigo: 'BOD-01', placeholder: false },
  { n3: 'BODEGON-LICORERIA', macroN1: 'BODEGONES', codigo: 'BOD-02', placeholder: false },
  { n3: 'MAYORISTA CON FUERZA DE VENTA', macroN1: 'MAYORISTAS', codigo: 'MAY-01', placeholder: false },
  { n3: 'MAYORISTA SIN FUERZA DE VENTA', macroN1: 'MAYORISTAS', codigo: 'MAY-02', placeholder: false },
  { n3: 'NANO DISTRIBUIDOR', macroN1: 'MAYORISTAS', codigo: 'MAY-03', placeholder: false },
  { n3: 'SUB-DISTRIBUIDOR', macroN1: 'MAYORISTAS', codigo: 'MAY-04', placeholder: false },
  { n3: 'RESTAURANTE', macroN1: 'ON PREMISE / FOODSERVICE', codigo: 'FS-01', placeholder: false },
  { n3: 'FAST FOOD', macroN1: 'ON PREMISE / FOODSERVICE', codigo: 'FS-02', placeholder: false },
  { n3: 'LUNCHERIA / CAFETERIA', macroN1: 'ON PREMISE / FOODSERVICE', codigo: 'FS-03', placeholder: false },
  { n3: 'HOTEL / POSADA', macroN1: 'ON PREMISE / FOODSERVICE', codigo: 'FS-04', placeholder: false },
  { n3: 'CATERING / INSTITUCIONAL', macroN1: 'ON PREMISE / FOODSERVICE', codigo: 'FS-05', placeholder: false },
  { n3: 'TIENDA DE CONVENIENCIA', macroN1: 'TIENDAS ESPECIALIZADAS', codigo: 'TE-01', placeholder: false },
  { n3: 'TIENDA PARA BEBE', macroN1: 'TIENDAS ESPECIALIZADAS', codigo: 'TE-02', placeholder: false },
  { n3: 'PIÑATERIA / TIENDA DE REGALO', macroN1: 'TIENDAS ESPECIALIZADAS', codigo: 'TE-03', placeholder: false },
]

export const MACROS_N1 = [...new Set(SEGMENTOS.map((s) => s.macroN1))]
